class Dict():
    """docstring for Dict."""

    courses=["html",
                "css",
                "jquery",
                "angular",
                "bootstrap",
                "nodejs",
                "c",
                "c++",
                "java",
                "php",
                "python",
                "ruby",
                "js",
                "kotlin",
                "r",
                "django",
                "spring",
                "hybernet",
                "flask",
                "ci",
                "pyqt",
                "tkinter",
                "SKLEARN",
                "ml",
                "artificial intellegence",
                "big data",
                "deep learning",
                "data analytics"]



    python=[{'topic':'Introduction',
                'url':'python_introduction'},
                {'topic':'Variable and Keywords',
                'url':'python_Variable_and_Keywords'},
                {'topic':'Types',
                'url':'python_Types'},
                {'topic':'Operators',
                'url':'python_Operators'},
                {'topic':'Expressions',
                'url':'python_Expressions'},
                {'topic':'Control Statements',
                'url':'python_Control_Statements'},
                {'topic':'Data_Structure',
                'url':'python_Data_Structure'},
                {'topic':'Functions',
                'url':'python_Functions'},
                {'topic':'Modules',
                'url':'python_Modules'},
                {'topic':'Packages',
                'url':'python_Packages'},
                {'topic':'Object Oriented Programming',
                'url':'python_Object_Oriented_Programming'},
                {'topic':'Exceptions',
                'url':'python_Exceptions'},
                {'topic':'Standard Library',
                'url':'python_Standard_Library'},
                {'topic':'Testing',
                'url':'python_Testing'}]

    cpp =[
            {'topic':'Introduction',
            'url':'cpp_introduction'},
            {'topic':'Program Structure',
            'url':'cpp_program_structure'},
            {'topic':'Input and Output',
            'url':'cpp_input_output'},
            {'topic':'C++ Basics',
            'url':'cpp_basics'},
            {'topic':'Data Types',
            'url':'cpp_data_types'},
            {'topic':'Constants',
            'url':'cpp_constants'},
            {'topic':'Operators',
            'url':'cpp_operator'},
            {'topic':'Control Statements',
            'url':'cpp_control_statements'},
            {'topic':'Arrays',
            'url':'cpp_array'},
            {'topic':'Strings',
            'url':'cpp_strings'},
            {'topic':'Functions',
            'url':'cpp_functions'},
            {'topic':'Parameter Passing Techniques',
            'url':'cpp_parameter_passing'},
            {'topic':'Classes and Objects',
            'url':'cpp_class_object'},
            {'topic':'Constructor and Destructor',
            'url':'cpp_constructor_destructor'},
            {'topic':'Operator Overloading',
            'url':'cpp_op_overloading'},
            {'topic':'Type Conversion',
            'url':'cpp_type_conversion'},
            {'topic':'Inheritance',
            'url':'cpp_inheritance'},
            {'topic':'Types Of Inheritance',
            'url':'cpp_types_inheritance'},
            {'topic':'Polymorphism',
            'url':'cpp_polymorphism'},
            {'topic':'Abstract Class',
            'url':'cpp_abstact_class'},
            {'topic':'File Handling',
            'url':'cpp_file_handling'},
            {'topic':'Exception Handling',
            'url':'cpp_exception_handling'}
    ]

    javatutpython=[
                {'topic':'overview',
                'url':'/jtpython_overview'},
                {'topic':'environment setup',
                'url':'/jtpython_environment_setup'},
                {'topic':'basic syntax',
                'url':'/jtpython_basic_syntax'},
                {'topic':'variable types',
                'url':'/jtpython_variable_types'},
                {'topic':'basic operators',
                'url':'/jtpython_basic_operators'},
                {'topic':'decision making',
                'url':'/jtpython_decision_making'},
                {'topic':'loops',
                'url':'/jtpython_loops'},
                {'topic':'numbers',
                'url':'/jtpython_numbers'},
                {'topic':'strings',
                'url':'/jtpython_strings'},
                {'topic':'list',
                'url':'/jtpython_list'},
                {'topic':'tuples',
                'url':'/jtpython_tuples'},
                {'topic':'dictionary',
                'url':'/jtpython_dictionary'},
                {'topic':'date and time',
                'url':'/jtpython_date_and_time'},
                {'topic':'functions',
                'url':'/jtpython_functions'},
                {'topic':'modules',
                'url':'/jtpython_modules'},
                {'topic':'files i/o',
                'url':'/jtpython_files_io'},
                {'topic':'exceptions handling',
                'url':'/jtpython_exceptions_handling'},
                {'topic':'object oriented',
                'url':'/jtpython_object_oriented'},
                {'topic':'regular expressions',
                'url':'/jtpython_regular_expressions'},
                {'topic':'cgi programming',
                'url':'/jtpython_cgi_programming'},
                {'topic':'mysql databases access',
                'url':'/jtpython_mysql_databases_access'},
                {'topic':'network programming',
                'url':'/jtpython_network_programming'},
                {'topic':'sending email using smtp',
                'url':'/jtpython_sending_email_using_smtp'},
                {'topic':'multithreaded programming',
                'url':'/jtpython_multithreaded_programming'},
                {'topic':'xml processing',
                'url':'/jtpython_xml_processing'},
                {'topic':'gui programming(tkinter)',
                'url':'/jtpython_gui_programming'},
                {'topic':'extension programming with c',
                'url':'/jtpython_extension_programming_with_c'},
                {'topic':'questions and answers',
                'url':'/jtpython_questions_and_answers'},
                {'topic':'quick guide',
                'url':'/jtpython_quick_guide'},
                {'topic':'tools/utilities',
                'url':'/jtpython_tools'},
                {'topic':'useful resources',
                'url':'/jtpython_useful_resources'}
    ]

    c=      [{'topic':'computer basics',
            'url':'c_computer_basics'},
            {'topic':'software concepts',
            'url':'c_software_concepts'},
            {'topic':'steps for program',
            'url':'c_steps_for_program'},
            {'topic':'introduction to c',
            'url':'c_introduction_to_c'},
            {'topic':'creating and running c',
            'url':'c_creating_and_running_c'},
            {'topic':'tokens',
            'url':'c_tokens'},
            {'topic':'data types',
            'url':'c_data_types'},
            {'topic':'operators',
            'url':'c_operators'},
            {'topic':'expressions',
            'url':'c_expressions'},
            {'topic':'type casting',
            'url':'c_type_casting'},
            {'topic':'decision making statements',
            'url':'c_decision_making_statements'},
            {'topic':'iteration statements',
            'url':'c_iteration_statements'},
            {'topic':'arrays',
            'url':'c_arrays'},
            {'topic':'strings',
            'url':'c_strings'},
            {'topic':'functions',
            'url':'c_functions'},
            {'topic':'predefined libraries',
            'url':'c_predefined_libraries'},
            {'topic':'nested functions',
            'url':'c_nested_functions'},
            {'topic':'types of variables',
            'url':'c_types_of_variables'},
            {'topic':'storage classes',
            'url':'c_storage_classes'},
            {'topic':'passing array to functions',
            'url':'c_passing_array_to_functions'},
            {'topic':'preprocessor directives',
            'url':'c_preprocessor_directives'},
            {'topic':'pointers',
            'url':'c_pointers'},
            {'topic':'structures',
            'url':'c_structures'},
            {'topic':'union',
            'url':'c_union'},
            {'topic':'file management',
            'url':'c_file_management'},
            {'topic':'command line argument',
             'url':'c_command_line_argument'}

    ]
    def __init__(self):
        super(Dict, self).__init__()
